### ISSUE TITLE
incomplete documentation for mongodb

### ISSUE THREAD

**Issue by sicarrots** [stof/StofDoctrineExtensionsBundle#120]
According to doc i've added to config.yml:

```
stof_doctrine_extensions:
    default_locale: %locale%
    mongodb:
        default:
            timestampable: true
            sluggable: true
    orm:
        default:
            timestampable: true
            sluggable: true
```

It's working for orm but not for odm. To get timestampable and sluggable working in odm i need to add explicit service listener:

```
services:
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
            - { name: doctrine.odm.mongodb.default_event_subscriber }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
            - { name: doctrine.odm.mongodb.default_event_subscriber }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
```

Maybe is there another solution or doc should be extended?
