### ISSUE TITLE
Unknown Entity namespace alias 'OneOfMyBundle'. 

### ISSUE THREAD

**Issue by mikeSimonson** [stof/StofDoctrineExtensionsBundle#128]
Hi,

I have been using symfony2.

I have an entities with customs Repository.
Everything work fine.

I have now added the DoctrineExtensionsBundle using this https://github.com/stof/StofDoctrineExtensionsBundle/blob/master/Resources/doc/index.rst
I added it because i needed the Translatable extension of that bundle.

So i configured that Translatable extension

In config.yml

``` yaml
doctrine:
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            auto_mapping: true
            default:
                mappings:
                    translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo-doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            translatable: true
```

But with or without the auto_mapping: true I only get an internal Error : "Unknown Entity namespace alias 'OneOfMyBundle' "

Does anyone has any clue where that error come from ?
It look like I need more than one Entity manager but the doc I have found about it is very little and only speaks about multiple EM for multiple DB.

I have tested this and got the same result with both symfony 2.0.9 and 2.0.12

Thanks for your help
