### ISSUE TITLE
Bundle "gedmo_translatable" does not exist

### ISSUE THREAD

**Issue by jeanmonod** [stof/StofDoctrineExtensionsBundle#132]
When configuring like in the doc:

```
orm:
    auto_generate_proxy_classes: %kernel.debug%
    mappings:
        gedmo_translatable:
            type: annotation
            prefix: Gedmo\Translatable\Entity
            dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
            alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
```

I got the following issue:

```
/www/test>app/console
    [InvalidArgumentException]
    Bundle "gedmo_translatable" does not exist or it is not enabled.  
```

Any hint?
