### ISSUE TITLE
TranslatableLisnter never being invoked

### ISSUE THREAD

**Issue by wowdesigns** [stof/StofDoctrineExtensionsBundle#135]
Hello,

Here is my config file
```
# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver: %database_driver%
                host: %database_host%
                port: %database_port%
                dbname: %database_name%
                user: %database_user%
                password: %database_password%
                charset: UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_translatable:
                        is_bundle: false
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo-doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                    gedmo_loggable:
                        is_bundle: false
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo-doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping

stof_doctrine_extensions:
    default_locale: en_US
    class:
        translatable: GD\SiteBundle\Listener\TranslatableListener
    orm:
        default:
            timestampable: true
            sluggable: true
            loggable: true
```

Any idea why the TranslatableListener is not getting invoked?

It doesn't run even when the configuration is like this:-
```
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
            translatable: true
            sluggable: true
            loggable: true
```

-------

With Version 1.0.x my configuration is like this, and the TranslationListener is invoked on every request. 

```
# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver: %database_driver%
                host: %database_host%
                port: %database_port%
                dbname: %database_name%
                user: %database_user%
                password: %database_password%
                charset: UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            StofDoctrineExtensionsBundle: true

stof_doctrine_extensions:
    default_locale: en_US
    translation_fallback: true
    orm:
        default:
            timestampable: true
            sluggable: true
            translatable: true
            loggable: true
```

Can you spot something incorrect?

Thanks!
