### ISSUE TITLE
Problem with installation?

### ISSUE THREAD

**Issue by neilferreira** [stof/StofDoctrineExtensionsBundle#136]
Hi,

In order to use the Loggable functionality I've had to adjust my ORM config to be as such:

```
orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        entity_managers:
            default:
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
```

I've basically added the entity manager, but doing so gets me this error:

```
Unrecognized options "auto_mapping" under "doctrine.orm"
```

If I remove the auto_mapping key, then I cannot load any of my other entiries or I get the error "Unknown Entity namespace alias 'FooSiteBundle'

I I don't add the entity mapping for gedmo_loggable I get the following error when loading  the repository manager that stores the versions, 'Unknown Entity namespace alias 'StofDoctrineExtensionsBundle'. '

I can't find any open source project using the loggable functionality that I can test with,  can you verify that this bundle still actually works?

cheers
