### ISSUE TITLE
Fatal error with Timestampable since updating 

### ISSUE THREAD

**Issue by wheelsandcogs** [stof/StofDoctrineExtensionsBundle#139]
With the latest code (sf2.1, master versions of bundles) if I have Timestampable config enabled, I get the following error:

```
Fatal error: Call to undefined method Doctrine\Bundle\MongoDBBundle\Mapping\Driver\XmlDriver::getLocator() in .../vendor/gedmo/doctrine-extensions/lib/Gedmo/Mapping/ExtensionMetadataFactory.php on line 157
```

My config is as follows:

```
doctrine_mongodb:
    connections:
        default:
            server: %mongodb_server%
            options:
                connect: true
    default_database: %mongodb_database%
    document_managers:
        default:
            auto_mapping: true

stof_doctrine_extensions:
    default_locale: en_GB
    mongodb:
        default:
            timestampable: true
```

It was working fine at the end of last week, so I've been trying to spot if a change to doctrine mongodb odm in the last couple of days (e.g. a refactoring of getLocator()) could have broken this but I can't seem to see anything obvious here: https://github.com/doctrine/mongodb-odm/commits/master.

Any ideas?
