### ISSUE TITLE
InvalidConfigurationException: Unrecognized options "auto_mapping" under "doctrine.orm" 

### ISSUE THREAD

**Issue by Ziiweb** [stof/StofDoctrineExtensionsBundle#141]
Hi,

after following the instructions to install this bundle, Im getting this error:

>    InvalidConfigurationException: Unrecognized options "auto_mapping" under "doctrine.orm"</quote>

I found other issues related to this problem but i did not find a solution..

This is my config.yml:

<pre><code>
doctrine:
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        entity_managers:
            default:
                mappings:
                    StofDoctrineExtensionsBundle: ~
</pre></code>
and this below is my composer.phar:

<pre><code>
{
    "name": "symfony/framework-standard-edition",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": { "": "src/" }
    },  
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.1._",
        "doctrine/orm": "2.2._",
        "doctrine/doctrine-bundle": "dev-master",
        "twig/extensions": "dev-master",
        "symfony/assetic-bundle": "dev-master",
        "symfony/swiftmailer-bundle": "dev-master",
        "symfony/monolog-bundle": "dev-master",
        "sensio/distribution-bundle": "dev-master",
        "sensio/framework-extra-bundle": "dev-master",
        "sensio/generator-bundle": "dev-master",
        "jms/security-extra-bundle": "1.1._",
        "jms/di-extra-bundle": "1.0._",
        "gedmo/doctrine-extensions": "dev-master",
        "friendsofsymfony/user-bundle": "_",
        "stof/doctrine-extensions-bundle": "dev-master",
        "knplabs/knp-menu-bundle" : "1.1._",
        "knplabs/knp-menu" : "1.1.*",
        "sonata-project/exporter" : "dev-master",
        "sonata-project/jquery-bundle" : "dev-master",
        "sonata-project/block-bundle" : "dev-master",
        "sonata-project/cache-bundle" : "dev-master",
        "sonata-project/admin-bundle" : "dev-master",
        "sonata-project/user-bundle" : "dev-master",
        "sonata-project/doctrine-orm-admin-bundle" : "dev-master"
</pre></code>

Javi

**Comment by fundup** [comment]
Using this config and SYmfony 2.7 
```
orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                month: DoctrineExtensions\Query\Mysql\Month
                year: DoctrineExtensions\Query\Mysql\Year
```

I have an error : 
Attempted to load class "Month" from namespace "DoctrineExtensions\Query\Mysql".
Did you forget a "use" statement for another namespace?

I tried to add a use statement in my reposotory...
If anyone as an idea ?
