### ISSUE TITLE
Incorrect mapping using Symfony 2.1RC1

### ISSUE THREAD

**Issue by xantos05** [stof/StofDoctrineExtensionsBundle#149]
I'm trying to migrate my Symfony 2.0 application to version 2.1RC1. However my translation entities are being mapped incorrectly.

Then i receive error messages like:
- PageTranslation::$id must be protected
- No identifier/primary key specified for Entity "Company\TestBundle\Entity\CategoryTranslation" sub class of "Gedmo\Translatable\Entity\MappedSuperclass\AbstractTranslation". Every Entity must have an identifier/primary key.

Since my own entities should be mapped to a added "auto_mapping: true" to my config.yml so it looks like this at the moment.

```
# Doctrine Configuration
doctrine:
    dbal:        
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8                    
    orm:
        auto_generate_proxy_classes: %kernel.debug%        
        connection: default
        auto_mapping: true                
        mappings:                        
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                is_bundle: false
            gedmo_translator:
                type: annotation
                prefix: Gedmo\Translator\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                is_bundle: false                                                                                  

stof_doctrine_extensions:
    default_locale: en
    translation_fallback: true
    orm:
        default:               
            translatable: true
            sluggable: true

```

When i remove the getters and setters from my Translation class everything is ok. When i run the generate-entities command using the command-line, all my Translation classes are being mapped and changed like this:

```
<?php

namespace Company\TestBundle\Entity;

use Gedmo\Translatable\Entity\MappedSuperclass\AbstractTranslation;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Table(name="category_translation", indexes={
 *      @ORM\index(name="category_translation_idx", columns={"locale", "object_class", "foreign_key", "field"})
 * })
 * @ORM\Entity(repositoryClass="Gedmo\Translatable\Entity\Repository\TranslationRepository")
 */
class CategoryTranslation extends AbstractTranslation
{
    /**
     * All required columns are mapped through inherited superclass
     */


    /**
     * @var integer $id
     */
    private $id;

    /**
     * @var string $locale
     */
    private $locale;

    ......

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set locale
     *
     * @param string $locale
     * @return CategoryTranslation
     */
    public function setLocale($locale)
    {
        $this->locale = $locale;

        return $this;
    }

    .....
}
```

What is going on here?
