### ISSUE TITLE
The correct configuration for MongoDB

### ISSUE THREAD

**Issue by alfonsofega** [stof/StofDoctrineExtensionsBundle#154]
I am starting with a new Symfony 2.1 project. I want to use this bundle but I get this error:

InvalidArgumentException: Invalid stof_doctrine_extensions config: document manager "default" not found.

I have the last version of all.

My configuration:

``` yaml
# Doctrine MongoDB Configuration
doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options:
                connect: true
    default_database: test_database
    document_managers:
        default:
            connection: 'default'
            auto_mapping: true
            mappings:
                gedmo_translatable:
                    type: annotation
                    prefix: Gedmo\Translatable\Document
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Document"
                    alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                    is_bundle: false
                gedmo_translator:
                    type: annotation
                    prefix: Gedmo\Translator\Document
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Document"
                    alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
                    is_bundle: false
                gedmo_loggable:
                    type: annotation
                    prefix: Gedmo\Loggable\Document
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Document"
                    alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                    is_bundle: false
                gedmo_tree:
                    type: annotation
                    prefix: Gedmo\Tree\Document
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Document"
                    alias: GedmoTree # this one is optional and will default to the name set for the mapping
                    is_bundle: false

stof_doctrine_extensions:
    default_locale: %locale%
    mongodb:
        default:
            timestampable: true
            sluggable: true
```

How can I solve this problem? Thanks
