### ISSUE TITLE
Configuration issue: should I use an entity manager or a connection to enable extensions?

### ISSUE THREAD

**Issue by vitorbrandao** [stof/StofDoctrineExtensionsBundle#173]
In the docs, section [Activate the extensions you want](https://github.com/stof/StofDoctrineExtensionsBundle/blob/master/Resources/doc/index.rst#activate-the-extensions-you-want), it is said:

> For each of your **entity manager**, declare the extensions you want to enable

The problem is, if I use one of my configured entity managers I get:

> The Doctrine **connection** "noiselabs" referenced in service "stof_doctrine_extensions.listener.timestampable" does not exist.

However using a connection id (`noiselabs_blog`)  works. So, what should be used in the configuration: an **entity manager or a connection id**?

For reference, my configuration:

``` YAML
doctrine:
    dbal:
        connections:
            noiselabs_blog:
                driver:   pdo_mysql
                host:     127.0.0.1
                # ...
    orm:
        entity_managers:
            noiselabs:
                connection: noiselabs_blog
                mappings:
                    NoiseLabsBlogBundle:
                        type:   annotation
                        dir:    Model
                        prefix: NoiseLabs\BlogBundle\Model

stof_doctrine_extensions:
    orm:
        noiselabs:
            timestampable:  true
            blameable:      true
```
