### ISSUE TITLE
Auto Load not Working

### ISSUE THREAD

**Issue by kimmellj** [stof/StofDoctrineExtensionsBundle#183]
I get the following error message on the remote environment but not locally and am stumped as to what could be causing it.

```
Whoops, looks like something went wrong.
1/1 FatalErrorException: Error: Class 'Gedmo\Tree\Entity\MappedSuperClass\AbstractClosure' not found in /var/www/api/src/Foo/CatalogBundle/Entity/AttributeClosure.php line 17
in /var/www/api/src/Foo/Entity/AttributeClosure.php line 17
```

PHP Version: PHP 5.3.10

``` json
[
    {
        "name": "doctrine/common",
        "version": "2.3.x-dev",
        "source": {
            "type": "git",
            "url": "https://github.com/doctrine/common",
            "reference": "bb0aebbf234db52df476a2b473d434745b34221c"
        }
    },
    {
        "name": "doctrine/data-fixtures",
        "version": "dev-master",
        "source": {
            "type": "git",
            "url": "https://github.com/doctrine/data-fixtures.git",
            "reference": "50e7e644984f17038224f6fcd02c2b7c20147980"
        }
    },
    {
        "name": "doctrine/dbal",
        "version": "2.3.x-dev",
        "source": {
            "type": "git",
            "url": "https://github.com/doctrine/dbal",
            "reference": "fd45c6f6baa618d871f3201fabe76df5043abb1e"
        }
    },
    {
        "name": "doctrine/doctrine-bundle",
        "version": "dev-master",
        "target-dir": "Doctrine/Bundle/DoctrineBundle",
        "source": {
            "type": "git",
            "url": "git://github.com/doctrine/DoctrineBundle.git",
            "reference": "6c6e2cfbb29324b3a5b4b883be41a1d4c5f791c1"
        }
    },
    {
        "name": "doctrine/doctrine-migrations-bundle",
        "version": "dev-master",
        "target-dir": "Doctrine/Bundle/MigrationsBundle",
        "source": {
            "type": "git",
            "url": "https://github.com/doctrine/DoctrineMigrationsBundle.git",
            "reference": "99c0192804134a8c1d0588777bd98bdbc2dbb554"
        }
    },
    {
        "name": "doctrine/inflector",
        "version": "dev-master",
        "source": {
            "type": "git",
            "url": "https://github.com/doctrine/inflector.git",
            "reference": "43ddae8c65425b41a1f62940dc0717b65b097ae0"
        }
    },
    {
        "name": "doctrine/migrations",
        "version": "dev-master",
        "source": {
            "type": "git",
            "url": "https://github.com/doctrine/migrations",
            "reference": "e1f6efcd94993b493de5c6a413cbc327ea9c0caa"
        }
    },
    {
        "name": "doctrine/orm",
        "version": "2.3.x-dev",
        "source": {
            "type": "git",
            "url": "git://github.com/doctrine/doctrine2.git",
            "reference": "fdd0af34e6fced967b8751bc3e4792c11ef86d57"
        }
    },
    {
        "name": "gedmo/doctrine-extensions",
        "version": "dev-master",
        "source": {
            "type": "git",
            "url": "git://github.com/l3pp4rd/DoctrineExtensions.git",
            "reference": "93349ad3ab200c7aa69237355c4ee811d359d160"
        }
    },
    {
        "name": "stof/doctrine-extensions-bundle",
        "version": "dev-master",
        "target-dir": "Stof/DoctrineExtensionsBundle",
        "source": {
            "type": "git",
            "url": "https://github.com/stof/StofDoctrineExtensionsBundle",
            "reference": "4a17550d8b101c5aafc56c9950149aa189b8402d"
        }
    },
    {
        "name": "symfony/symfony",
        "version": "dev-master",
        "source": {
            "type": "git",
            "url": "git://github.com/symfony/symfony.git",
            "reference": "4ecaa10f8d71ba8f34872cfeac01bac669690ec0"
        }
    }
]
```

src/Foo/CatalogBundle/Entity/AttributeClosure.php

``` php
<?php                                                                                                                                                                                                                      

namespace Foo\CatalogBundle\Entity;

use Gedmo\Tree\Entity\MappedSuperClass\AbstractClosure;
use Doctrine\ORM\Mapping as ORM;

/**
 * AttributeClosure
 *
 * @ORM\Table(name="attribute_closure")
 * @ORM\Entity
 */
class AttributeClosure extends AbstractClosure
{

}
```

app/config/config.yml

``` yml
…
doctrine:
    dbal:
        default_connection:   ids 
        connections:
            ids:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
                mapping_types:
                    enum: string
            ids2:
                driver:   %database_driver2%
                host:     %database_host2%
                port:     %database_port2%
                dbname:   %database_name2%
                user:     %database_user2%
                password: %database_password2%
                charset:  UTF8
                mapping_types:
                    enum: string
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager:   ids 
        entity_managers:
            ids:
                connection:       ids 
                mappings:
                    GedmoLoggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        #alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false
                    GedmoTree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity/MappedSuperclass"
                        #alias: GedmoTree # this one is optional and will default to the name set for the mapping
                        is_bundle: false
...
```

Let me know if you need any more details.

Thanks, 
Jamie
