### ISSUE TITLE
Mappings not created when type set to yml

### ISSUE THREAD

**Issue by marshmn** [stof/StofDoctrineExtensionsBundle#195]
I'm unable to generate mappings when type is set to yml or xml. 

From a fresh install of Symfony 2.2 I have added the StofDoctrineExtensionsBundle and added the following to my config.yml:

``` yaml
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"

        entity_managers:
            default:
                mappings:
                    AcmeDemoBundle: ~
                    gedmo_loggable:
                        type: yml
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                        is_bundle: false

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            loggable: true

```

When I then run 'php app/console doctrine.mapping.info' I get the following error:

```
[Exception]                                                                                                        
  You do not have any mapped Doctrine ORM entities according to the current configuration. If you have entities or   
  mapping files you should check your mapping configuration for errors.
```

If I change 'type: yml' to 'type: annotation' in the above config and run doctrine.mapping.info again I get the expected output:

```
Found 2 mapped entities:
[OK]   Gedmo\Loggable\Entity\MappedSuperclass\AbstractLogEntry
[OK]   Gedmo\Loggable\Entity\LogEntry
```

Shouldn't this behave the same regardless of what 'type' is set to?

Thanks,
Matt
