### ISSUE TITLE
Impossible to use Loggable with MongoDB 

### ISSUE THREAD

**Issue by marcospallanzani** [stof/StofDoctrineExtensionsBundle#220]
Hello,

I'm trying to use the extension Loggable with a Mongo database. I actually had already added (and successfully) the loggable extensions to my project but I was using the ORM solution. 

I now decided to use the ODM one but it's not working and I don't understand why. 

I debugged the code and it seems that there is no subscription events for my custom listener.

here is my configuration for the stof_doctrine_extensions and the doctrine_mongodb as defined in my app/config/config.yml file:

```
stof_doctrine_extensions:
    orm:
        default:
            timestampable:  true
    mongodb:
        default:
            loggable:       true
    class:
        loggable:    Client\MainBundle\Listener\KnmLoggableListener

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: user_activity
    default_connection: 'default'
    default_document_manager: 'default'
    document_managers:
        default:
            connection: default
            auto_mapping: true
            mappings:
                loggable:
                    type: annotation
                    prefix: Knm\Client\MainBundle\Document\Log
                   dir: "%kernel.root_dir%/../src/Knm/Client/MainBundle/Document/Log"
                    alias: ClientMainBundleDocumentLog 
```

where the class Client\MainBundle\Listener\KnmLoggableListener is my custom loggable listener (which is working if I activate the loggable extension under the orm part of the conf here above).

One last thing: I already use the connection to the mongo db to insert other documents and it perfectly works, so I excluded any causes connected to the database connection.

Can anyone help me with this problem I'm experiencing? 

Thanks in advance.

Marco.
