### ISSUE TITLE
Listener "SoftDeleteableListener" was not added to the EventManager!

### ISSUE THREAD

**Issue by USvER** [stof/StofDoctrineExtensionsBundle#221]
When i add this to doctrine.orm:

``` yml
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
```
