### ISSUE TITLE
Uploadable sets value to null if no image is selected

### ISSUE THREAD

**Issue by electricBonfire** [stof/StofDoctrineExtensionsBundle#223]
I am having an issue with Uploadable. I have added an `avatar` property to my user. If the user updates his profile but does not change their `avatar` the column in the database gets set to null. 

I noticed in the docs it said to add this to the form builder: `->add('avatar')` 
This was rendering a text input and not a file input. 

I had to use this to get the file input: `->add('avatar', 'file', array('required' => false, 'data_class' => null))`

I am guessing something might not be configured correctly, The upload does seem to work when actually trying to update the `avatar` however.

I have the following in my config.yml:

```
doctrine:
   orm:
       auto_mapping: true
.....
stof_doctrine_extensions:
    orm:
        default:
            uploadable: true
```
