### ISSUE TITLE
Sortable breaks other extensions

### ISSUE THREAD

**Issue by thomas2411** [stof/StofDoctrineExtensionsBundle#230]
When I use only sortable on Entity, it works OK but when I use it with others (timestamable and blamable to be specific) it breaks rest of them.

My configuration is:

``` yml
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            sluggable: true
            timestampable: true
            blameable: true    
            sortable: true
```

In my Entity:

``` yml
MyBundle\Entity\Screen:
    type:  entity
    table: screen
    repositoryClass: ScreenRepository
    id:
        id:
            type: integer
            unique: true
            generator:
                strategy: AUTO
    fields:
        nazwa:
            type: string
            length: 256
        opublikowany:
            type: boolean
            nullable: true
        kolejnosc:
          type: integer
          gedmo:
            - sortablePosition
        created:
          type: datetime
          gedmo:
            timestampable:
              on: create
        updated:
          type: datetime
          gedmo:
            timestampable:
              on: update    
    manyToOne:
        createdBy:
          targetEntity: User
          joinColumn:
              name: created_by
              referencedColumnName: id
              nullable: true   
          gedmo:
            blameable:
              on: create   
        updatedBy:
          targetEntity: User
          joinColumn:
              name: updated_by
              referencedColumnName: id
              nullable: true   
          gedmo:
            blameable:
              on: update   
```

So when I turn off sortable, created, updated, createdBy, updatedBy work OK. But when I turn on sortable, all those 4 fields are set to null (date to 0000-00-00 00:00:00 to be specific)
