### ISSUE TITLE
Translatable and Sluggable issue

### ISSUE THREAD

**Issue by picks44** [stof/StofDoctrineExtensionsBundle#232]
I'm using Translatable and Sluggable on an Entity, and they are working OK. But now, I also would like to translate the slug field, so I changed my entity to
```
/**
     * @Gedmo\Translatable
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(length=255, unique=false)
     */
    private $slug;
```
Then I edited my transation and the slug field translated OK.

Now when I try to access my article on the front-end, I get a 404...

My route is
```
front_article:
    pattern:  /{_locale}/article/{slug}
    defaults: { _controller: MyOwnBundle:Front:article }
    requirements:
        _locale: en|fr
```
And I'm using ParamConverter in my contoller 
```
public function articleAction(Article $article)
    {
        return $this->render('MyOwnBundle:Front:article.html.twig', array(
                'article'      => $article
            ));
    }
```
And the error
```
 My\OwnBundle\Entity\Article object not found.
404 Not Found - NotFoundHttpException 
```
What is wrong or missing ?
