### ISSUE TITLE
Listener priority

### ISSUE THREAD

**Issue by flip111** [stof/StofDoctrineExtensionsBundle#242]
Hi, i would like to change the priority of the [`LocaleListener`](https://github.com/stof/StofDoctrineExtensionsBundle/blob/master/EventListener/LocaleListener.php) because i want to fetch the user with some other entity that is translatable. For this i need priority 8 or higher to have the right locale available before the firewall is invoked.

I tried to override it like this:

```
    stof_doctrine_extensions.event_listener.locale:
        class: MyVendor\UserBundle\EventListener\DoctrinePriorityLocaleSubscriber
        arguments:
          - @stof_doctrine_extensions.listener.translatable
        tags:
            - { name: kernel.event_subscriber }
```

However it's not working:
- not throwing error, but:
- fires another query for each translation (while the default translation is in the same table)
  and i think i'm doing it wrong. Some things i noticed:
- two instances `Gedmo\Translatable\TranslatableListener` are created, where i set the right locale on one and the other one is the one that is used to check the current locale.
- i noticed that the original service is private (public = false) and maybe this cause a problem that it can not be overwritten.
- Manually changing `Gedmo\Translatable\TranslatableListener::$locale` to my default locale (= `en` and not `en_US`) solves all problems (but this is not the correct way of doing things)

Is there any "official" way to support configuring this listener ??
