### ISSUE TITLE
Just doesnt work, followed the install couple times. Even manually configuring acts strangely

### ISSUE THREAD

**Issue by ghost** [stof/StofDoctrineExtensionsBundle#248]
Hi,

I followed the installation a couple times, but i cant seem to get the softdeletable activated..
- Dont have multiple EMs
- Tried the short syntax thing, makes no difference
- The testsuite of the gedmo package doesnt fail
- Not using a 2.0.x version of Doc ORM, considering the BC break message.

Deps

```
"symfony/symfony": "~2.5",
"doctrine/orm": "~2.2,>=2.2.3",
"doctrine/doctrine-bundle": "~1.2",
"stof/doctrine-extensions-bundle": "~1.1@dev",
```

Config

```
doctrine:
    orm:
        entity_managers:
            default:
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            softdeleteable: true
```

The only thing that works after this config is removing through the EM, DQL or finding/selecting doesnt work:

```
// works
$em->remove($entity);
$em->flush();

// doesnt
 - delete from...
 - ->find... or select... 
```

Selecting only works after i added the filter manually somewhere:

```
$em->getConfiguration()->addFilter('softdelete', 'Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter');
$em->getFilters()->enable('softdelete');
```

And even when i added the filter manually, removing through DQL does something weird also. While it should set the deletedAt column, it checks where it's null and then still deletes..:

```
DELETE FROM Test WHERE (a_id = ?) AND (Test.deletedAt IS NULL) ["164"] []
```
