### ISSUE TITLE
Misuse of orm key in configuration file ?

### ISSUE THREAD

**Issue by dorian53** [stof/StofDoctrineExtensionsBundle#257]
Hello,

in the extension configuration section for "orm", the keys ("default") are said to reference entity managers. In fact, they seem to be used as dbal connection names ("dbal:connections:`<name>`").

In your documentation :

``` yml
# app/config/config.yml
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:    # <-- this name
            tree: true
            timestampable: false
        other:
            timestampable: true
```

In your StofDoctrineExtensionsExtension.php

``` php
foreach ($config['orm'] as $name => $listeners) {
    foreach ($listeners as $ext => $enabled) {
        $listener = sprintf('stof_doctrine_extensions.listener.%s', $ext);
        if ($enabled && $container->hasDefinition($listener)) {
            $attributes = array('connection' => $name /* used here */);
            // [...]
        }
    }
}
```

Thanks
