### ISSUE TITLE
Set relative path in uploadable default file path 

### ISSUE THREAD

**Issue by maidmaid** [stof/StofDoctrineExtensionsBundle#274]
Hello !

In doc, it says :

```yml
# app/config/config.yml
stof_doctrine_extensions:
    uploadable:
        default_file_path: %kernel.root_dir%/../web/uploads
```
Why not use relative path from ``/web`` folder ? With ``default_file_path: uploads``, the ``asset`` function works, but not with absolute path. In addition, the project location can change, without making change in path of entity recorded in database.
