### ISSUE TITLE
Documentation lacks information

### ISSUE THREAD

**Issue by frenetic** [stof/StofDoctrineExtensionsBundle#292]
Hello all o/
First, thanks for the awesome effort :+1: 

Just installed this bundle to make use of **TimestampableEntity** trait.
I had a really hard time trying to make it work :crying_cat_face:

Documentation provided on https://github.com/stof/StofDoctrineExtensionsBundle/blob/master/Resources/doc/index.rst was not clear enough.

It took me almost an hour to discover I had to put the following piece of code on my ``config.yml``
```yaml
stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
```

Please, add this information to the documentation.
Also, please, revalidate the documentation to check if there are something else missing.
