### ISSUE TITLE
Disabling translatable

### ISSUE THREAD

**Issue by swalkinshaw** [stof/StofDoctrineExtensionsBundle#31]
Not sure if this is a bug, but I'm getting an error when I try to generate entities:

[Doctrine\ORM\Mapping\MappingException]  
  No identifier/primary key specified for Entity 'Stof\DoctrineExtensionsBundle\Entity\Translation'. Every Entity must have an identifier/primary key.

This error happens even when I disable the Translatable service in my config.yml:

``` yaml
stof_doctrine_extensions:
     orm:
      default:
          translatable: false
          timestampable: true
```
