### ISSUE TITLE
Symfony3 - Translateable tries to insert double on not default language

### ISSUE THREAD

**Issue by larsalbrecht** [stof/StofDoctrineExtensionsBundle#318]
I have setup a new project. If the user is not in the default language and adds a new entity to the database, it does not work:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '...' for key 'lookup_unique_idx'

I removed the key and reloaded the page. Now I have the same entry with the same language in the database, instead of default (en) and user selected (de). 

This is my config (locale is en)

```
stof_doctrine_extensions:
    default_locale: %locale%
    translation_fallback: true
    persist_default_translation: false
    orm:
        default:
            timestampable: true
            sluggable: true
            translatable: true
```

Bug or misconfiguration?
