### ISSUE TITLE
If my updatedBy field is not null, value is updated by null on update

### ISSUE THREAD

**Issue by JJarrie** [stof/StofDoctrineExtensionsBundle#339]
Hello,

I'm working with the version 1.2.2 of the bundle and Symfony 2.8.2.

When I'm create an entity and persist him, my fields createdBy and updatedBy is correctly field, if I try to update the same entity, when I flush the object manager the updatedBy fields is set to null, but if I update again the same entity the field is ok. I have testing some part of code (mine and yours) and not see the origin of the problem.

My config :

In config.yml I've added :

```yaml
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            blameable: true
```

services.yml

```yaml
services:
    gedmo.listener.blameable:
        class: AppBundle\Listener\BlameableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, ['@annotation_reader'] ]
            - [ setUserValue, ['test'] ]
```

My sources files (in minimalist project for testing) :

```php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\MyEntity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class DefaultController extends Controller
{
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction(Request $request)
    {
        // replace this example code with whatever you need
        return $this->render(
            'default/index.html.twig',
            array(
                'base_dir' => realpath($this->container->getParameter('kernel.root_dir').'/..'),
            )
        );
    }

    /**
     * @Route("/create")
     */
    public function createAction()
    {
        $a = new MyEntity();
        $a->setMyValue((new \DateTime())->format('d/m/Y H:i:s'));
        $this->getDoctrine()->getManager()->persist($a);
        $this->getDoctrine()->getManager()->flush();
        return new Response();
    }

    /**
     * @return Response
     * @Route("/edit")
     */
    public function editAction()
    {
        $a = $this->getDoctrine()->getRepository(MyEntity::class)->find(1);
        $a->setMyValue((new \DateTime())->format('d/m/Y H:i:s'));
        $this->getDoctrine()->getManager()->flush();
        return new Response();
    }
}
```

```php
<?php

namespace AppBundle\Entity;

use AppBundle\BlameableTrait;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Blameable\Traits\BlameableEntity;

/**
 * Class MyEntity
 * @ORM\Entity()
 */
class MyEntity
{
    /**
     * @var
     * @ORM\Column(type="integer")
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string")
     */
    protected $myValue;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     * @return MyEntity
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getMyValue()
    {
        return $this->myValue;
    }

    /**
     * @param mixed $myValue
     * @return MyEntity
     */
    public function setMyValue($myValue)
    {
        $this->myValue = $myValue;

        return $this;
    }

    use BlameableEntity;
}
```

```php
<?php

namespace AppBundle\Listener;

class BlameableListener extends \Gedmo\Blameable\BlameableListener
{
    public function getFieldValue($meta, $field, $eventAdapter)
    {
        return $this->user;
    }
}
```

Best regards

**Comment by grago** [comment]
Hi, did you ever get this problem solved? I'm having this exact behavior. Thanks.

**Comment by grago** [comment]
Nevermind, i've solved this by implementing an extension of of BlameableListener

```php

namespace AppBundle\Listener;

class BlameableListener extends \Gedmo\Blameable\BlameableListener
{
    protected $securityStorage;

    public function getFieldValue($meta, $field, $eventAdapter)
    {   

        if($this->securityStorage) return $this->securityStorage->getToken()->getUser();

    }

    public function setSecurityStorage($securityStorage)
    {
        $this->securityStorage = $securityStorage;
    }

}
```

services.yml

```yml
  gedmo.listener.blameable:
    class: AppBundle\Listener\BlameableListener
    tags:
        - { name: doctrine.event_subscriber, connection: default }
    calls:
        - [ setSecurityStorage, [ '@security.token_storage' ] ]
        - [ setAnnotationReader, [ '@annotation_reader' ] ]

```
