### ISSUE TITLE
Translatable Twig trans filter integration

### ISSUE THREAD

**Issue by leandro980** [stof/StofDoctrineExtensionsBundle#345]
Hi,
is there a way to integrate it with twig trans filter?
Cannot find documentation.
Thanks

**Comment by stof** [comment]
I don't understand what you want to integrate. The Gedmo translatable extension will ensure that the getter on your entity gives you the translated value.

This bundle takes care of configure the extension to use the same locale than the Symfony translator.

**Comment by leandro980** [comment]
I'm using personal translation, i've tryed default [config.yml](https://symfony.com/doc/master/bundles/StofDoctrineExtensionsBundle/index.html#step-3-add-the-extensions-to-your-mapping) and this version (both the same problem)

```
parameters:
    locale: it
orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
            menu_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: MenuTree
                is_bundle: false
            menu_translatable:
                type: annotation
                prefix: App\Entity\Menu\MenuItem
                dir: "%kernel.root_dir%/../src/App/Entity/Menu"
                alias: GedmoTranslatable
                is_bundle: false
            menu_translator:
                type: annotation
                prefix: App\Entity\Menu\MenuItemTranslation
                dir: "%kernel.root_dir%/../src/App/Entity/Menu"
                alias: GedmoTranslator
                is_bundle: false
```

Where

```
/**
 *
 * @Gedmo\Tree(type="nested")
 * @Gedmo\TranslationEntity(class="App\Entity\Menu\MenuItemTranslation")
 * @ORM\Table(name="mnu_item")
 * @ORM\Entity(repositoryClass="App\Repository\Menu\MenuItem")
 */
class MenuItem { 
// ..

   /**
     *
     * @var string
     * @Gedmo\Translatable
     * @ORM\Column(name="label", type="string", length=255, nullable=true)
     */
    private $label;
   
   /**
     * @Gedmo\Locale
     * Used locale to override Translation listener`s locale
     * this is not a mapped field of entity metadata, just a simple property
     * and it is not necessary because globally locale can be set in listener
     */
    private $locale;
    
    /**
     * @ORM\OneToMany(targetEntity="\App\Entity\Menu\MenuItemTranslation",
     *                mappedBy="object",
     *                cascade={"persist", "remove"})
     */
    private $translations;

    /**
     * 
     * @return type
     */
    public function getTranslations(){
        return $this->translations;
    }

    /**
     * 
     * @param \Cowbell\Entity\Menu\MenuItemTranslation $t
     */
    public function addTranslation(MenuItemTranslation $t){
        if (!$this->translations->contains($t)) {
            $this->translations[] = $t;
            $t->setObject($this);
        }
    }
    
    public function setTranslatableLocale($locale){
        $this->locale = $locale;
    }

   public function getLabel(){
        return $this->label;
   }
}
```

And

```
/**
 * Description of MenuItemTranslation
/*
 * @ORM\Entity
 * @ORM\Table(name="mnu_menu_item_translations",
 *     uniqueConstraints={@ORM\UniqueConstraint(name="lookup_unique_idx", columns={
 *         "locale", "mnu_menu_item_id", "field"
 *     })}
 * )
 */
class MenuItemTranslation extends AbstractPersonalTranslation {
    
    /**
     * Convenient constructor
     *
     * @param string $locale
     * @param string $field
     * @param string $value
     */
    public function __construct($locale, $field, $value)
    {
        $this->setLocale($locale);
        $this->setField($field);
        $this->setContent($value);
    }

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Menu\MenuItem", inversedBy="translations")
     * @ORM\JoinColumn(name="mnu_menu_item_id", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $object;
    
}
```

I've added translation and they're saved in right table but in twig, using item.getLabel() it prints always the default value (e.g. Test, app.request.getLocale prints it).

MenuItem
![MenuItem](http://oi63.tinypic.com/o86wcx.jpg)

MenuItemTranslation
![MenuItemTranslation](http://i67.tinypic.com/qoez6c.png)

**Comment by leandro980** [comment]
Ok, obviously my fault.

I turned back on default config

```
doctrine
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            menu_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: MenuTree
                is_bundle: false
            gedmo_translatable:
                type: annotation
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                is_bundle: false
            gedmo_translator:
                type: annotation
                prefix: Gedmo\Translator\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                is_bundle: false
```

Then i changed the stof config 'cos my site is all in english and i need italian translation

```
stof_doctrine_extensions:
    default_locale: "%locale%" #this is my error, just remove this line to set it back to en_US
    translation_fallback: true
    orm:
        default:
            tree: true
            translatable: true
            sluggable: true
```
I'm sorry. 
Closing this.
