### ISSUE TITLE
[SF4] How to use loggable properly?

### ISSUE THREAD

**Issue by baris1892** [stof/StofDoctrineExtensionsBundle#366]
Hi, I'm trying to include this bundle to my Symfony 4 project.

My `stof_doctrine_extensions.yaml` looks like this:
```
stof_doctrine_extensions:
    orm:
        default:
            loggable: true
```

And my entity:
```
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @Gedmo\Loggable()
 * @ORM\Table(name="versionable_entity")
 */
class VersionableEntity
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer",nullable=false)
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=false)
     * @Gedmo\Versioned()
     */
    private $name;
}
```
I'm not sure if I missed anything, but the following code throws an error:
```
 $versionableEntity = new VersionableEntity();
 $versionableEntity->setName("name 1");
 $this->entityManager->persist($versionableEntity);
 $this->entityManager->flush();
```

```
HTTP 500 Internal Server Error: MappingException
The class 'Gedmo\Loggable\Entity\LogEntry' was not found in the chain configured namespaces App\Entity
```

So is there any working example?
Thanks in advance!

**Comment by petegore** [comment]
Hi,

I think you have to tell Doctrine that the Bundle uses its own entities for some behavior (loggable, translatable, translator, and tree) : 

```yaml 
# config/doctrine.yaml
doctrine:
    orm:
        mappings:
            gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mapping
                        is_bundle: false
```

See here at Step 3 : https://symfony.com/doc/current/bundles/StofDoctrineExtensionsBundle/index.html
