### ISSUE TITLE
Issue @Gedmo\Blameable(on="update") set NULL value

### ISSUE THREAD

**Issue by ArturTovmasyan** [stof/StofDoctrineExtensionsBundle#371]
When i run my symfony2 command, and in command i change DB data, after flush update field is NULL, but create field is ok, why? But not CLI process, all is ok!

**Comment by dracken** [comment]
We're having the same behavior, using YAML.  We're also using timestampable, which is working on both create and update.  Being that this is nearly a year old, has any maintainer reviewed this issue?

`createdBy: gedmo: blameable: on: create` works
`updatedBy: gedmo: blameable: on: update` fails with a null value

**Comment by ArturTovmasyan** [comment]
Thanks for answer.

**Comment by janklan** [comment]
Not sure how relevant it is, but I had a similar issue - I did not work out the exact cause, but while searching for it, I found that I was configuring the Blameable behaviour directly in my service definition. At first I was using Gedmo directly, then I switched to Stof's bundle. I removed the service definitions and my issue went away.

**Comment by czachor** [comment]
I can confirm @janklan answer: I had unnecessarily repeated listener configuration from Gedmo like this:
```
stof_doctrine_extensions:
  default_locale: pl_PL
  orm:
    default:
      blameable: true

services:
  Gedmo\Blameable\BlameableListener:
    tags:
      - { name: doctrine.event_listener, event: 'prePersist' }
      - { name: doctrine.event_listener, event: 'onFlush' }
      - { name: doctrine.event_listener, event: 'loadClassMetadata' }
```

Just leave it as below:
```
stof_doctrine_extensions:
  default_locale: pl_PL
  orm:
    default:
      blameable: true

**Comment by czachor** [comment]
I can confirm @janklan answer: I had unnecessarily repeated listener configuration from Gedmo like this:
```
stof_doctrine_extensions:
  default_locale: pl_PL
  orm:
    default:
      blameable: true

services:
  Gedmo\Blameable\BlameableListener:
    tags:
      - { name: doctrine.event_listener, event: 'prePersist' }
      - { name: doctrine.event_listener, event: 'onFlush' }
      - { name: doctrine.event_listener, event: 'loadClassMetadata' }
```

Just leave it as below:
```
stof_doctrine_extensions:
  default_locale: pl_PL
  orm:
    default:
      blameable: true
