### ISSUE TITLE
Unable to extend LoggerListener

### ISSUE THREAD

**Issue by lologhi** [stof/StofDoctrineExtensionsBundle#375]
Hi!

I'm using Loggable and FOSOauthServer and I'd like the Loggable extension to store the name of the user linked to the API Client (like that: `getClient()->getUser()->getUsername()`) in the `ext_log_entries.username` field. So I tried to extends the LoggerListener to add `OAuthStorage`, something like:

```php
class ApiLoggerListener extends LoggerListener
{
    public function __construct(LoggableListener $loggableListener, TokenStorageInterface $tokenStorage = null, AuthorizationCheckerInterface $authorizationChecker = null, OAuthStorage $OAuthStorage = null)
    {
        $this->OAuthStorage = $OAuthStorage;
        parent::__construct($loggableListener, $tokenStorage, $authorizationChecker);
    }

    public function onKernelRequest(GetResponseEvent $event)
    {
        // ... copy pasted the LoggerListener's onKernelRequest content.

        $this->loggableListener->setUsername($this->OAuthStorage->getAccessToken($token->getToken())->getClient()->getUser()->getUsername());
    }
}
```

When I first tried it, by modifying `LoggerListener`, it was working. But now that I try to clean my code, I have two issues:

1. `Unrecognized option "logger" under "stof_doctrine_extensions.class"`. Is there another way to override the default `LoggerListener` class?
2. `Cannot autowire service "App\Listener\ApiLoggerListener": argument "$loggableListener" of method "__construct()" references class "Gedmo\Loggable\LoggableListener" but no such service exists. You should maybe alias this class to the existing "stof_doctrine_extensions.listener.loggable" service.` I tried to manually wire this service following the `loggable.xml` config, but it ended with `Too few arguments to function App\Listener\ApiLoggerListener::__construct(), 0 passed`...

Thank you for your help!

**Comment by lologhi** [comment]
My bad, I didn't know how to override a class. I just needed to specify my overriding in `config/services.yaml`:

```
    App\Listener\ApiLoggerListener:
        arguments:
            $loggableListener: '@stof_doctrine_extensions.listener.loggable'
            $tokenStorage: '@?security.token_storage'
            $authorizationChecker: '@?security.authorization_checker'
            $OAuthStorage : '@?fos_oauth_server.storage'
        public: true
        tags:
        - { name: kernel.event_subscriber }
    # override default Logger class
    stof_doctrine_extensions.event_listener.logger: '@App\Listener\ApiLoggerListener'
```
