### ISSUE TITLE
This repository can be attached only to ODM MongoDB tree listener

### ISSUE THREAD

**Issue by velkony** [stof/StofDoctrineExtensionsBundle#379]
Hi,
after I released my project on Symfony 4 in prod, I received the following error when clearing the cache
```
In AbstractTreeRepository.php line 47:
This repository can be attached only to ODM MongoDB tree listener
```
When I switche it to dev mode, It works.

services.yaml:

   ```
 Gedmo\Tree\TreeListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
            - { name: doctrine_mongodb.odm.event_subscriber }
        calls:
            - method: setAnnotationReader
              arguments:
                  - "@annotation_reader"

```
stof_doctrine_extensions.yaml:
```
stof_doctrine_extensions:
    mongodb:
        default:
            tree: true
            sluggable: true
            timestampable: true
    default_locale: cz_CZ
```
Document:
```
use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @MongoDB\Document(repositoryClass="Gedmo\Tree\Document\MongoDB\Repository\MaterializedPathRepository", collection="service")
 * @Gedmo\Tree(type="materializedPath", activateLocking=false)
 */
class Service {
    /**
     * @MongoDB\Id
     */
    private $id;
/**
     * @MongoDB\Field(type="string")
     * @Gedmo\TreePathSource
     */
    private $name;

    /**
     * @MongoDB\Field(type="string")
     * @Gedmo\TreePath(separator="/", appendId=false)
     */
    private $path;

    /**
     * @Gedmo\TreeParent
     * @MongoDB\ReferenceOne(targetDocument="service")
     */
    private $parent;

    /**
     * @Gedmo\TreeLevel
     * @MongoDB\Field(type="int")
     */
    private $level;

    /**
     * @Gedmo\TreeLockTime
     * @MongoDB\Field(type="date")
     */
    private $lockTime;

```
