### ISSUE TITLE
Problems in configValidate when have multiple EM's

### ISSUE THREAD

**Issue by Koc** [stof/StofDoctrineExtensionsBundle#38]
``` yaml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            read:
                mappings:
                    StofDoctrineExtensionsBundle: ~
                    FooTerritorialBundle: ~
            write:
                mappings:
                    StofDoctrineExtensionsBundle: ~
                   FooTerritorialBundle: ~

stof_doctrine_extensions:
    orm:
        read: ~
        write: ~
```

Validation trying get `doctrine.dbal.read_connection` but as you see I'm setted up `default` as `default_connection`.
