### ISSUE TITLE
Blameable on update seems to be not working with persist and flush in Synfony 3.x

### ISSUE THREAD

**Issue by ranjzith** [stof/StofDoctrineExtensionsBundle#387]
Hi All,

I am working on a PHP project with symfony 3.4 and doctrine 2.6, we have a blameable field on an entity, when I first create the entity the blameable field is getting set properly but on update the value is set to empty/null in database. This use to work before we had upgraded symfony (from 2.x to 3.x) and other dependent libraries to higher versions. Could some one shed some light on this,

This is sample from my orm file
```
manyToOne:
    LastUpdateUser:
        targetEntity: My\UserEntity
        gedmo:
            blameable:
                on: update
```
On update scenario,
```
$entityManager->persist($entity);
$entityManager->flush();
```
after executing the above, the last update user value is set to empty/null in database. Any lead on this would be a great help.

Thanks.
