### ISSUE TITLE
Probleme non existent service stof_doctrine_extensions.listener.translatable

### ISSUE THREAD

**Issue by libressence** [stof/StofDoctrineExtensionsBundle#396]
When i add 

    admin.page:
        class: App\Admin\PageAdmin
        arguments: [~, App\Entity\Page, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Page }

in services.yaml,

i have a problem after type command bin/console cache:clear :
The service "sonata_translation.admin.extension.gedmo_translatable" has a dependency on a non-existent service "stof_doctrine_extensions.listener.translatable".

Why ??

**Comment by spolischook** [comment]
You should enable it in configuration:
```yaml
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            translatable: true # <--- this will enable listener
```
