### ISSUE TITLE
Metadadata cache generates empty files each timefor Loggable and Softdeleteable

### ISSUE THREAD

**Issue by pohlaniacz** [stof/StofDoctrineExtensionsBundle#411]
Hi, I've had high usage of memcached and as fix I've change provider to `Doctrine\Common\Cache\PhpFileCache` and on production I've looked for cache files and my entity class cache looks fine are and not changing but Loggable and Softdeleteable (which I'm using) generates file with empty content which CacheProvider make as:

```<?php return unserialize('a:2:{s:8:"lifetime";N;s:4:"data";a:0:{}}');```

Loggable and Softdeletetable is working fine, but not for all my entities. Cache provider instead (imo) looks for all classes? 

My config is:
```
doctrine:
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore
                dql:
                    string_functions:
                        GROUP_CONCAT: Chipin\CoreBundle\Query\Mysql\GroupConcat
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                        is_bundle: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true

stof_doctrine_extensions:
    orm:
        default:
            loggable: true
            softdeleteable: true
```

In every doc I've looked (ie. https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/metadata-drivers.html#core-metadata-drivers ) they say that metada cache is not changing, so these is weird behaviour? My symfony version is 3.4, newset doctrine extensions, and stof bundle in 1.3.0.
