### ISSUE TITLE
Documentation not up to date since 1.5.0 and gedmo/doctrine-extensions 3.0.0

### ISSUE THREAD

**Issue by PierrickMartos** [stof/StofDoctrineExtensionsBundle#417]
The Symfony documentation isn't up to date since the  release of `1.5.0` that used `gedmo/doctrine-extensions:3.0.0` : https://symfony.com/doc/master/bundles/StofDoctrineExtensionsBundle/configuration.html#add-the-extensions-to-your-mapping

Since the `3.0.0`, source files of doctrine extensions have moved from `/lib/Gedmo` to `/src` (more info: https://github.com/Atlantic18/DoctrineExtensions/releases/tag/v3.0.0)

Here is the right updated config:
```yaml
# app/config/config.yml
# (or config/packages/doctrine.yaml if you use Flex)
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translator/Entity"
                        alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
                        alias: GedmoTree # (optional) it will default to the name set for the mapping
                        is_bundle: false
```

Without the updated path, this can lead to this kind of error:

```
In AbstractDoctrineExtension.php line 84:
!!
!!    Bundle "loggable" does not exist or it is not enabled.
```
