### ISSUE TITLE
SoftDeleted entities are not filtered/excluded from database results

### ISSUE THREAD

**Issue by Jayfrown** [stof/StofDoctrineExtensionsBundle#439]
**Describe the bug**

I use `SoftDeleteable` entities in my API Platform project, but I've noticed a couple issues. I had initially thought this to be an issue in API Platform, but I can reproduce the issue with a simple controller outside of API Platform.

- If I delete an entity, the `deleted_at` field is updated as expected;
- If I `$doctrine->getRepository(TestEvent::class)->find($id);`, the entity I just (soft)deleted is simply returned.

**To Reproduce**
```yaml
# stof_doctrine_extensions.yaml
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            sluggable: true
            timestampable: true
            blameable: true
            loggable: true
            softdeleteable: true
```
```yaml
# doctrine.yaml
doctrine:
    dbal:
        driver: pdo_mysqli
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_general_ci
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        resolve_target_entities:
            App\Model\AbstractIdentityInterface: App\Entity\AbstractIdentity
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity/"
                alias: GedmoLoggable
                is_bundle: false
```
```php
<?php
// TestEvent.php

namespace App\Entity\Planning;

use App\Repository\Planning\TestEventRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Blameable\Traits\BlameableEntity;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=TestEventRepository::class)
 * @ORM\Table(name="test_events")
 * @Gedmo\Loggable
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=true, hardDelete=false)
 * @UniqueEntity("id")
 */
class TestEvent
{
    use TimestampableEntity;
    use BlameableEntity;
    use SoftDeleteableEntity;

    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Gedmo\Versioned
     * @Groups("read", "write")
     */
    private $name;

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
    
    // ..
}
```
```php
<?php
// TestController.php

namespace App\Controller;

use App\Entity\Planning\TestEvent;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;

class TestController extends AbstractController
{
    /**
     * @Route("/test_event/{id}", name="test_event_show")
     */
    public function show(ManagerRegistry $doctrine, string $id): JsonResponse
    {
        $entity = $doctrine->getRepository(TestEvent::class)->find($id);

        if (!$entity) {
            throw $this->createNotFoundException(
                'No entity found for id '.$id
            );
        }

        $resp = [
            'id' => $entity->getId(),
            'name' => $entity->getName(),
            'deleted_At' => $entity->getDeletedAt(),
        ];

        return new JsonResponse($resp);
    }
}
```

**Evidence**

At first the entity exists as normal, not yet SoftDeleted:
```
GET https://localhost/test_event/1ec875b8-4ec1-690e-875c-f7d92857e532
{
    "id": "1ec875b8-4ec1-690e-875c-f7d92857e532",
    "name": "test_1",
    "deleted_At": null
}
```

After deleting the entity, the `deleted_at` field is set as expected:
```
❯ bin/console dbal:run-sql "SELECT deleted_at FROM test_events WHERE id = 0x1ec875b84ec1690e875cf7d92857e532;"
 --------------------- 
  deleted_at           
 --------------------- 
  2022-02-06 16:00:10  
 --------------------- 
```

However the controller still returns the entity instead of a 404:
```
GET https://localhost/test_event/1ec875b8-4ec1-690e-875c-f7d92857e532
{
    "id": "1ec875b8-4ec1-690e-875c-f7d92857e532",
    "name": "test_1",
    "deleted_At": {
        "date": "2022-02-06 16:00:10.000000",
        "timezone_type": 3,
        "timezone": "Europe/Amsterdam"
    }
}
```

**Expected behavior**
I had expected that the `SoftDeleteableFilter` would exclude the SoftDeleted entity from DB query results, thus preventing the `->find($id)` from returning the entity, and thus my controller would return a 404.

Is this expectation wrong, have I misconfigured something, or could this be a bug in upstream DoctrineExtensions?

**Additional context**
ref: https://github.com/api-platform/api-platform/issues/2128
